### ISSUE TITLE
Breaking issue

### ISSUE THREAD

**Issue by stijlbreuk-dev** [cablespaghetti/helmfile-docker#3]
The latest update created an issue in our CI/CD pipeline

I think it might be an upstream error at helm-git;
ARG HELM_GIT_VERSION=0.10.0

We Reverted to 3.3.4.1 to fix it.

The error we had:

```
Error: looks like "git+[OUR-HELM-CHARTS-GIT-REPO-URL]@/" is not a valid chart repository or cannot be reached: plugin "helm-git" exited with error
```

It seems like an error that occurs when using a git helm repo with an empty path. The issue is discussed here:

https://github.com/aslafy-z/helm-git/issues/131

**Comment by cablespaghetti** [comment]
I've fixed this in the latest tag (3.4.2) by switching back to the old version (0.8.1). Thanks for letting me know. We don't use helm-git so don't notice problems.
